### PR TITLE
CB-13124: Add option for native scroll-to-top on WebView

### PR DESCRIPTION
**Pull request by lunaru**
### Platforms affected
iOS

### What does this PR do?
Adds "StatusBarDefaultScrollToTop" option to allow developer to re-enable native scroll-to-top behavior on the WebView

The motivation for this is described here: https://issues.apache.org/jira/browse/CB-13124

### CODE REVIEW

**Comment by hengwoon** [comment]
This would be extremely useful since it allows re-scrolling while a momentum scroll is in progress. Would be great if we can get this support in

**Comment by lunaru** [comment]
Hey guys, I'd love to get some feedback on this PR. Let me know if there are any questions. We're now using the fork in production and it's helped a lot with the scroll-to-top quirkiness that a pure javascript implementation exhibits.

**Comment by lunaru** [comment]
Hey, just checking in on this PR as it's been very quiet on this project. Let me know if there are any questions about the fix.

**Comment by Hirbod** [comment]
When will this important feature land?

**Comment by lunaru** [comment]
@alsorokin @jcesarmobile hey guys, I know you've probably been busy with the iPhone X related fixes, but I'd love to get this branch merged in as well. Let me know if there are any questions.

**Comment by jcesarmobile** [comment]
@lunaru the PR looks good to me, but new features should be discussed on the developer list. Can you send a mail to dev@cordova.apache.org?

**Comment by lunaru** [comment]
@jcesarmobile thanks, email sent.

**Comment by jcesarmobile** [comment]
@lunaru I've not seen the mail on the list

**Comment by lunaru** [comment]
@jcesarmobile does sending to the email list require any permissions? I sent it to dev@cordova.apache.org. I'll try again with my other email address.

**Comment by jcesarmobile** [comment]
@lunaru both of them just arrived, will answer there, thanks!

**Comment by lunaru** [comment]
@jcesarmobile hey -- i haven't seen any updates on this. any concerns? It would be really nice to have this in the main branch.

**Pull request merged**
