### PR TITLE
README: Fix issue tracker link

### PR DESCRIPTION
**Pull request by janpio**
wrong component name in search

### CODE REVIEW

**Comment by jcesarmobile** [comment]
I think it should be better to just change the component to `"cordova-plugin-statusbar"`. Right now it redirects to the one you used, but if some day CB-9742 is closed, the url will probably stop working.
Also, it would be good if you report the issue and use the issue id on the title, it's good to track even small changes like this one.

**Comment by janpio** [comment]
Good catch at the individual issue being linked - not intended.

As long as the PULL_REQUEST_TEMPLATE.md doesn't really work for README changes (doesn't effect any platform, testing is irrelevant) I don't really see the use in the overhead for creating an issue. Or is there?

**Comment by lunaru** [comment]
+1 for this change. I was confused by this as well when I was looking for the issue tracker.

**Comment by filmaj** [comment]
I rebased / merged this in. Thanks @janpio !

**Comment by janpio** [comment]
(I actually still had this tab open for a issue, rebase etc later - sorry about that. But thanks for taking the initiative.)

**Pull request closed without merging**
