### PR TITLE
Stop "object has no method" errors on windows

### PR DESCRIPTION
**Pull request by Gillardo**
If you called show or hide, you would get an "object has no method"
error as getViewStatusBar would return null.

### CODE REVIEW

**Comment by nikhilkh** [comment]
Thanks for the contribution! I could not find your iCLA on file. Could you sign one and post it: http://www.apache.org/licenses/icla.txt

**Comment by Gillardo** [comment]
Sorry for stupid question, but what up i supposed to do with this? Print it and scan it?  Just type in the fields?  Where am i supposed to this once i have done what i am suppose to do?

**Comment by nikhilkh** [comment]
The full instructions for submission of the CLA are here: http://www.apache.org/licenses/#clas

**Comment by Gillardo** [comment]
@nikhilkh i have emailed the agreement to secretary@apache.org this morning for you.

**Comment by Gillardo** [comment]
This message acknowledges receipt of your ICLA, which has been filed in the Apache Software Foundation records.

If you have been invited as a committer, please advise the project PMC that your ICLA has been filed.

**Pull request closed without merging**
