### PR TITLE
CB-9841 - Allow iOS statusbar to animate hide/show

### PR DESCRIPTION
**Pull request by andreistanica**
I've modified the statusbar.js file to take 2 optional parameters on hide() and show(), animated and duration.
I've also changed the CDVStatusBar.m file to add read the parameters and correctly choose to animate or not the statusbar refresh.

If anyone has any questions regarding this feature let me know.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-statusbar/pull/37/commits/5e925e7b5bf11750d2935f452e8db78bd02c7c5a)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=mac-slave,platformName=android/artifact/) |
| [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/5//label=windows-slave,platformName=android/artifact/) |

**Comment by Hirbod** [comment]
Just came here to see if there is any solution to fade the status bar - and there we go. I don't understand why this isnt merged. Could you guys please add this into the plugin?

**Comment by ajarbol** [comment]
+1

**Comment by timbru31** [comment]
Any news on this, besides the merge conflict? Would love to see this merged.

**Comment by InternetExplorer8** [comment]
Any chance to get this merged? Any way we can help out?

**Comment by janpio** [comment]
Yes, someone could create a new PR where the merged conflict is resolved please, then someone could take a look.

In general: 
Is this an iOS only feature or is this also possible on other platforms?

**Comment by timbru31** [comment]
@janpio I've re-done the PR! 🎉  
AFAIK in Android you can't animate the status bar. (just did a quick Google search)

**Comment by timbru31** [comment]
Closing since I've re-done the PR in #123. I've kept your original commit @andreistanica - thank you very much for your contribution!

**Pull request closed without merging**
