### PR TITLE
Added javascript event on status bar tap

### PR DESCRIPTION
**Pull request by myster-t**
A fake scrollview is added to the CDVViewController's view (but it's in the background).  When the status bar is tapped, the scrollview will naturally be notified to scroll to the top and a new javascript event is fired.

This also has a fix for the webview frame calculations in the function hide.  The calculation is ignored when the status bar is overlaid on top of the webview.

### CODE REVIEW

**Comment by Hirbod** [comment]
Hello guys, I can't find any information about this nice and very useful function. How can I listen to this event? I've used https://github.com/j-mcnally/cordova-statusTap before, but this plugin is really buggy and breaks with Camera Plugin and IonicKeyboard-Plugin.

**Comment by Hirbod** [comment]
By the way, I've installed 1.0.0-dev via

```
cordova plugin add https://github.com/apache/cordova-plugin-statusbar/
```

and tried to listen to it with

```js
        window.addEventListener("statusTap", function() {});
```

but this function won't call.

**Comment by shazron** [comment]
Hi @Hirbod -- I created a new project, added the ios platform and the statusbar plugin (from github). Then added this:
```window.addEventListener("statusTap", function() { alert('tap'); });```

Launched the project, and tapped the statusbar. It immediately called my function. So I can't repro what you've seen. Can you try with a new project?

**Comment by Hirbod** [comment]
@shazron,

it seems like the Google Maps Plugin cause this error:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin

The plugin maintainer added support for the splashscreen plugin (https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/3fd283e722740459dc331f8f320ff4e078e44135 before, the mapview just killed the splashscreen) but it seems like the fake scrollview is not "on top" anymore, so the tap won't be triggerd. 

https://github.com/j-mcnally/cordova-statusTap worked well, but is very buggy and cause a lot of other problems. I know, this is out of your business, but the maps plugin maintainer is very busy and won't reply to any requests the next months, and I do know have any clue how to fix. Any idea, how I can be sure the fake-scroll-view is always on top?

**Comment by Hirbod** [comment]
At least it seems that https://github.com/j-mcnally/cordova-statusTap/blob/master/src/ios/TapToScroll.m is doing something right which doenst get interfere with other plugins. If you ask me, status-bar plugin should handle this cases, where another view could block it

**Comment by shazron** [comment]
Hi @Hirbod, 
Please file a separate issue at https://issues.apache.org/jira/browse/CB. I fear this will be buried in Github since it is already closed (and I don't have the karma to re-open it).

I'm sorry that this is harder than it should be -- we have no control over the mirrored projects on Github, unfortunately :/

**Comment by Hirbod** [comment]
Is it enough when I just link to our conversation? Or do I need to paste everything again there @shazron ? And thanks for your help!

**Comment by shazron** [comment]
If you could paste it in (only the relevant parts), that will be great. Thanks!

**Comment by Hirbod** [comment]
https://issues.apache.org/jira/browse/CB-8886

**Comment by DamilolaJegede** [comment]
+1

**Pull request closed without merging**
