### PR TITLE
chore(release): 3.0.0-dev

### PR DESCRIPTION
**Pull request by breautek**
There are already breaking changes in master, so version should represent a major release.

### CODE REVIEW

**Comment by yuzhakovvv** [comment]
@breautek when do you plan to make this release? Waiting for Android Status Bar fix
https://github.com/apache/cordova-plugin-statusbar/pull/171

**Comment by yuzhakovvv** [comment]
The problem is you merged it into master and updated README.md. It took more than an hour for me to figure out why I have the latest version but it doesn't work as expected.

**Comment by breautek** [comment]
As the version `-dev` indicates, it's a development version... not a production release. I cannot say when a production release will be made.

**Comment by expcapitaldev** [comment]
@breautek Hello!  can you say about production release?

**Pull request merged**
