### PR TITLE
Update readme with correct install command

### PR DESCRIPTION
**Pull request by Tarabass**

### CODE REVIEW

**Comment by danielbraun** [comment]
+1

**Comment by Nonsense331** [comment]
:shipit:

**Comment by shazron** [comment]
Actually, the plugin id is correct: https://github.com/apache/cordova-plugin-statusbar/commit/2d25d2ec4cebd76a04f7baf7d9ff1daed50966d2

The master docs in the repo are for the next release (master is the dev branch), the docs for the currently deployed release has the correct info: 
1. http://plugins.cordova.io/#/package/org.apache.cordova.statusbar
2. https://github.com/apache/cordova-plugin-statusbar/blob/r0.1.10/doc/index.md

**Comment by niels515** [comment]
Hi, does anyone know how to let the statusbar be #5f51b5, because it aint work on android 5.0.2. Thanks in advance

**Pull request closed without merging**
