### PR TITLE
CB-11858: (android) Add StatusBarStyle feature support for Android M+

### PR DESCRIPTION
**Pull request by urmx**
### Platforms affected

Android 6.0+ (API level 23+)

### What does this PR do?

This PR add StatusBarStyle feature support for Android 6.0+ (Marshmallow, API level 23+).

The existing "StatusBarStyle" preference is used, and according to the README.md, the possible case-insensitive values are:

- __default__: dark content (for light backgrounds)
- __lightcontent__: light content (for dark backgrounds)
- __blacktranslucent__: light content (for dark backgrounds)
- __blackopaque__: light content (for dark backgrounds)

This value can also be changed with the existing javascript functions:

- `StatusBar.styleDefault()`
- `StatusBar.styleLightContent()`
- `StatusBar.styleBlackTranslucent()`
- `StatusBar.styleBlackOpaque()`

The default value is "__lightcontent__" as specified in the README (thus backward compatible with the previous style).

### What testing has been done on this change?

- Default value (no StatusBarStyle parameter in config.xml) in a Cordova project on a Xperia Z3 Android 6.0.1
- The four StatusBarStyle values (lower and mixed cases) in config.xml in a Cordova project on a Xperia Z3 Android 6.0.1
- An invalid value "foo" in config.xml in a Cordova project on a Xperia Z3 Android 6.0.1
- The four StatusBar.style* methods in Chrome Remote Debugger on a Xperia Z3 Android 6.0.1
- Travis CI on this branch

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-statusbar/pull/78/commits/dd879140c42fa09c4274a76b9693be16e7f24f2a)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar-pr/46/)

 24 tests run, 0 skipped, 0 failed.

**Comment by tobiasviehweger** [comment]
Just fyi, I also did some things a long time ago in #64. Nothing did happen to it though....

**Comment by filmaj** [comment]
Two PRs for the same feature, wow! Thanks you two.

Have either of you signed an ICLA?

**Comment by tobiasviehweger** [comment]
@filmaj I did, actually.

**Comment by filmaj** [comment]
Cool, so we can fall back on your PR should @urmx be unable to. What about you, @urmx ?

**Comment by tobiasviehweger** [comment]
@filmaj @urmx We probably should also check about the blacktranslucent one. It seems we implemented that differently, but I din't quite remember why.. Also we have other defaults (default vs. lightcontent). I remember changing that to unify the behaviour across iOS and Android. @urmx Any thoughts?

**Comment by urmx** [comment]
@filmaj Yes, I also did 3 days ago.

**Comment by urmx** [comment]
@tobiasviehweger For the blacktranslucent behavior, I used this [plugin README](https://github.com/apache/cordova-plugin-statusbar/blob/master/README.md#statusbarstyleblacktranslucent):

> Use the blackTranslucent statusbar (light text, for dark backgrounds).

And I also had a look on [Apple Developer](https://developer.apple.com/reference/uikit/uibarstyle) about [blackTranslucent](https://developer.apple.com/reference/uikit/uibarstyle/1623394-blacktranslucent):

> Deprecated. Use black and set the isTranslucent property to true instead.

So it's the same as [black](https://developer.apple.com/reference/uikit/uibarstyle/1623396-black):

> Use a black background with light content.

And now both blackTranslucent and blackOpaque seem both deprecated in [UIStatusBarStyle](https://developer.apple.com/reference/uikit/uistatusbarstyle) (as you mentioned in your PR).

However, the [devgirl blog](http://devgirl.org/2014/07/31/phonegap-developers-guid/) you used as a reference state the opposite:

> The default and blacktranslucent values display black foreground text and icons.
> The lightcontent and blackopaque values display white foreground text and icons.

So if she's right, we also have to change this plugin README.

And for the default value in Android, I used lightContent (white on black) because it's backward compatible with the current style (white status bar text).

**Comment by filmaj** [comment]
Excellent, thanks for signing the ICLA!

Ping @hollyschinsky - can you check what @urmx and @tobiasviehweger mention here with respect to the blacktranslucent/blackopaque bits mentioned in your blog post?

**Comment by hollyschinsky** [comment]
@filmaj @urmx @tobiasviehweger It's a bit confusing with iOS because the status bar styling has changed several times and the `blacktranslucent` and `blackopaque` were deprecated in iOS7. 

My blog post was correct at the time but since the deprecation, the code in the StatusBar plugin has been updated. If you look at these methods now, those two deprecated styles are [only specifically applied when the version is pre 7](https://github.com/apache/cordova-plugin-statusbar/blob/master/src/ios/CDVStatusBar.m#L311-329). Otherwise that code will set it to the `UIStatusBarStyleLightContent` style - which is light foreground color (white text). This is the recommended setting [based on the apple docs](https://developer.apple.com/reference/uikit/uistatusbarstyle?language=objc) for those deprecated values. 

Also, make note that the `lightcontent` style preference is [automatically added to the platform config.xml](https://github.com/apache/cordova-plugin-statusbar/blob/master/plugin.xml#L59-L66) when you add the StatusBar plugin for iOS. So unless the developer specifically sets something else for that it in the root project config.xml, that is going to be what is set by default (not to be confused with the `default` style setting itself which is the opposite and dark foreground color (black text) for light backgrounds :/).

**Comment by markv** [comment]
@filmaj @urmx @tobiasviehweger can we get this PR merged? Thanks

**Comment by infil00p** [comment]
What happens when we test this on Android versions earlier than Android M? We currently support every Android version higher than API 19, so if we could get some more testing on this, that would be greatly appreciated.

**Comment by infil00p** [comment]
BTW: I'm going to go with this one since it merges more cleanly.  I'm going to close #64

**Pull request merged**
