### PR TITLE
New feature 'styleAndroidTranslucent'

### PR DESCRIPTION
**Pull request by aegliv**
Replaces the need for following plugin: ekuwang / cordova-plugin-statusbar

### CODE REVIEW

**Comment by FdezRomero** [comment]
This is awesome, I hope it gets merged soon :+1:

**Comment by MrARC** [comment]
I tested this feature on Motorola devices and it looks good, but this isn't the case when testing on Samsung and Sony Xperia devices, the statusbar doesn't look transparent and it's more like a dark gradient on the top.
screenshot_2016-04-19-17-43-15

This isn't the case when using apps like Google Play, they have a correct transparent statusbar whilst this not.

**Comment by FdezRomero** [comment]
Pushing this PR from oblivion: Maybe Google Play uses AppCompat and that's why it has a Material-style translucent status bar? I'm not sure if this is possible, just wondering.

Anyway, the option in @MrARC screenshot seems totally acceptable in Android 4.x devices, as I guess is the default behavior.

**Comment by MrARC** [comment]
Sorry, i forgot to say that the device was running Android 5.1, which is weird because Lollipop has support for translucent statusbar.

**Comment by FdezRomero** [comment]
@MrARC My bad, I thought it was 4.x because the home button is not a circle. The code in the PR just reverses the two flags set by the plugin. Maybe is related to OEMs changing this when they apply their own personalization to the UI?

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-statusbar/pull/51/commits/8467e8e51c9747f3fcdf0c611093486bc984b3ce)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=mac-slave,platformName=android/artifact/) |
| [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-statusbar/4//label=windows-slave,platformName=android/artifact/) |

**Comment by fentas** [comment]
+1 for **blacktranslucent**
For me transparent statusbar is only working with this pull. :/
Android 5.0.1.

Please merge.

**Comment by Ajaxy** [comment]
Will it be merged?

**Comment by gedeagas** [comment]
Great Work, @aegliv 

Please merge this.

**Comment by anymos** [comment]
+ 1, I would love to see this PR merged as well, especially that ekuwang / cordova-plugin-statusbar , is having a few bugs. Any ETA

**Comment by anymos** [comment]
Hmm, still having an issue the translucent status bar is visible only when in fullScreen mode :-( which is coming with it s own lot of issue. Anyway to make it transparent with a webOverlay without having to set the mode to immersive ?

**Comment by aegliv** [comment]
@MrARC & @anymos: 
It works for us on multiple Nexus, LG and Samsung devices without Immersive.
If it doesn't work for you, it is probably related to other settings made prior or after the flags are set with `styleAndroidTransparent()`.

Please try to debug the flag settings in `StatusBar.java`

**Comment by psirenny** [comment]
This pull isn't going anywhere. Is anyone - who is seeing a gradient instead of a translucent bar - willing to debug this in order to move it forward?

**Comment by kosssi** [comment]
👍

**Comment by FdezRomero** [comment]
If nobody is able to replicate the gradient status bar in 5.x+ and debug, let's move on and merge this already. It's ridiculous, it has been 9 months already!

**Comment by shamank** [comment]
Any reason it hasn't been already merged? I mean, for a Ionic development this is almost REQUIRED. The current bar looks completly bad when a modal or something involving an opaque background layer is displayed:

statusbar_50

What do you need or what are you waiting for to modernize this component?

**Comment by janpio** [comment]
The probability of merging pull requests are higher when they follow the Pull Request template of the project: https://github.com/apache/cordova-plugin-statusbar/blob/master/.github/PULL_REQUEST_TEMPLATE.md This one, for example, needs an issue at the official issue tracker.

**Comment by infil00p** [comment]
This looks incredibly similar to #78, if this is the case, I'm definitely going to be closing this one in favour of that PR that merges more cleanly.

**Pull request closed without merging**
