### PR TITLE
feat: update typings

### PR DESCRIPTION
**Pull request by timbru31**
This is part of [apache/cordova#39](https://github.com/apache/cordova/issues/39)

### Platforms affected

n/a - development with TypeScript

### Motivation and Context

updates typings as discussed in [apache/cordova#39](https://github.com/apache/cordova/issues/39)

### Description

Updates type definition header, missing statusTap event and modernizes function declaration.

### Testing

Manual testing via development in VSCode.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by timbru31** [comment]
I'd suggest to wait for #124 and #126, because I would need to increase the version in the header of the typings file.

**Comment by janpio** [comment]
Does it really make sense to have the version in there then? This just adds one more step to release a new version of the plugin, each time you do, right?

**Comment by timbru31** [comment]
Yes it adds a mandatory release step, but the user is able to see if the typings differ from the actual npm release - this could save some headache or searching.  
Because I've mostly worked with DefinitelyTyped, where it's needed for determining the version which is published to npm (see https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/), I've kept it.  
I guess it has both some pros and cons keeping the version in the header file.

Sidenote, if forgotten to increase the version it won't stop the typings from working, since it's a comment after all :)

**Comment by janpio** [comment]
Ok, we would have to add that to this super outdated and terrible documentation then: https://github.com/apache/cordova-coho/blob/master/docs/plugins-release-process.md

**Comment by timbru31** [comment]
Reminder/ToDo left on https://github.com/apache/cordova-coho/pull/233 - IMO this is ready for review :)

**Pull request merged**
